### ISSUE TITLE
Cannot load T5 Encoder in 8 bit even with colab

### ISSUE THREAD

**Issue by PansaLegrand** [huggingface/blog#1380] opened 2023-08-10 16:06 UTC
I try to run [Running IF with 🧨 diffusers on a Free Tier Google Colab](https://huggingface.co/blog/if),
and I have a problem loading the text encoder in 8 bits.

```
from transformers import T5EncoderModel
text_encoder = T5EncoderModel.from_pretrained(
    "DeepFloyd/IF-I-XL-v1.0",
    subfolder="text_encoder", 
    device_map="auto", 
    load_in_8bit=True, 
    variant="8bit"
)
```

Error message says:

```
You are loading your model in 8bit or 4bit but no linear modules were found in your model. Please double check your model architecture, or submit an issue on github if you think this is a bug.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-38-2ead1835a684>](https://localhost:8080/#) in <cell line: 2>()
      1 from transformers import T5EncoderModel
----> 2 text_encoder = T5EncoderModel.from_pretrained(
      3     "DeepFloyd/IF-I-XL-v1.0",
      4     subfolder="text_encoder",
      5     # device_map="auto",

4 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/parameter.py](https://localhost:8080/#) in __new__(cls, data, requires_grad)
     34             # For ease of BC maintenance, keep this path for standard Tensor.
     35             # Eventually (tm), we should change the behavior for standard Tensor to match.
---> 36             return torch.Tensor._make_subclass(cls, data, requires_grad)
     37 
     38         # Path for custom tensors: set a flag on the instance to indicate parameter-ness.

RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```

Anyone knows how to fix it ?

**Comment by williamberman** [comment] 2023-08-11 17:43
hey @PansaLegrand thanks for bringing this up, I'll take a look at it :)

**Comment by younesbelkada** [comment] 2023-08-17 10:02
hi @williamberman @PansaLegrand !
Check out this comment: https://github.com/huggingface/transformers/issues/25443#issuecomment-1680786465 , it seems to be a duplicate of the issue #25443 in transformers, can you try to install transformers from source?

**Closed** 2023-08-18 04:30 UTC
