### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'device_map')

### ISSUE THREAD

**Issue by afghaniiit** [huggingface/blog#1088] opened 2023-05-09 18:22 UTC
`generator = pipeline("text-generation", model=checkpoint, device_map="auto", torch_dtype=torch.float16)`

Traceback of **TypeError: ('Keyword argument not understood:', 'device_map')**

                                                                                                
                                                                                                
  ```
 /usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py:779 in pipeline     

 776 │   # Forced if framework already defined, inferred if it's None                         
   777 │   # Will load the correct model if possible                                            
   778 │   model_classes = {"tf": targeted_task["tf"], "pt": targeted_task["pt"]}               
 ❱ 779 │   framework, model = infer_framework_load_model(                                      
   780 │   │   model,                                                                           
   781 │   │   model_classes=model_classes,                                                     
   782 │   │   config=config,                                                                   
                                                                                                
 /usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py:262 in infer_framework_load_model                                                                     
                                                                                                
    259 │   │   │   │   )                                                                       
    260 │   │   │                                                                               
    261 │   │   │   try:                                                                        
 ❱  262 │   │   │   │   model = model_class.from_pretrained(model, **kwargs)                   
    263 │   │   │   │   if hasattr(model, "eval"):                                              
    264 │   │   │   │   │   model = model.eval()                                                
    265 │   │   │   │   # Stop loading on the first successful load.                            
                                                                                                
 /usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py:471 in from_pretrained                                                                                
                                                                                                
   468 │   │   │   )                                                                            
   469 │   │   elif type(config) in cls._model_mapping.keys():                                  
   470 │   │   │   model_class = _get_model_class(config, cls._model_mapping)                   
 ❱ 471 │   │   │   return model_class.from_pretrained(                                         
   472 │   │   │   │   pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, 
   473 │   │   │   )                                                                            
   474 │   │   raise ValueError(                                                                
                                                                                                
 /usr/local/lib/python3.10/dist-packages/transformers/modeling_tf_utils.py:2779 in              
 from_pretrained                                                                                
                                                                                                
   2776 │   │   │   model_kwargs["load_weight_prefix"] = load_weight_prefix + "/" + model_kwargs
   2777 │   │                                                                                   
   2778 │   │   # Instantiate model.                                                            
 ❱ 2779 │   │   model = cls(config, *model_args, **model_kwargs)                               
   2780 │   │                                                                                   
   2781 │   │   if from_pt:                                                                     
   2782 │   │   │   from .modeling_tf_pytorch_utils import load_pytorch_checkpoint_in_tf2_model 
                                                                                                
 /usr/local/lib/python3.10/dist-packages/transformers/modeling_tf_utils.py:170 in wrapped_init  
                                                                                                
    167 │   │   │   initializer(self, config, *args, **kwargs)                                  
    168 │   │   elif isinstance(config, PretrainedConfig):                                      
    169 │   │   │   if len(args) > 0:                                                           
 ❱  170 │   │   │   │   initializer(self, *args, **kwargs)                                     
    171 │   │   │   else:                                                                       
    172 │   │   │   │   initializer(self, config, *args, **kwargs)                              
    173 │   │   else:                                                                           
                                                                                                
 /usr/local/lib/python3.10/dist-packages/transformers/models/opt/modeling_tf_opt.py:873 in      
 __init__                                                                                       
                                                                                                
    870 │   config_class = OPTConfig                                                            
    871 │                                                                                       
    872 │   def __init__(self, config: OPTConfig, **kwargs):                                    
 ❱  873 │   │   super().__init__(config, **kwargs)                                             
    874 │   │   self.config = config                                                           
    875 │   │   self.model = TFOPTMainLayer(config, name="model")                              
    876                                                                                        
                                                                                            
 /usr/local/lib/python3.10/dist-packages/transformers/modeling_tf_utils.py:1131 in __init__    
                                                                                            
   1128 │   │   return "tf"                                                                    
   1129 │                                                                                      
   1130 │   def __init__(self, config, *inputs, **kwargs):                                     
 ❱ 1131 │   │   super().__init__(*inputs, **kwargs)                                            
   1132 │   │   if not isinstance(config, PretrainedConfig):                                   
   1133 │   │   │   raise ValueError(                                                          
   1134 │   │   │   │   f"Parameter config in `{self.__class__.__name__}(config)` should be an 
                                                                                            
 /usr/local/lib/python3.10/dist-packages/tensorflow/python/trackable/base.py:205 in            
 _method_wrapper                                                                               
                                                                                            
    202 │   previous_value = getattr(self, "_self_setattr_tracking", True)                     
    203 │   self._self_setattr_tracking = False  # pylint: disable=protected-access            
    204 │   try:                                                                                 
 ❱  205 │     result = method(self, *args, **kwargs)                                            
    206 │   finally:                                                                           
    207 │     self._self_setattr_tracking = previous_value  # pylint: disable=protected-access 
    208 │   return result                                                                      
                                                                                            
 /usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py:70 in error_handler    
                                                                                            
    67 │   │   │   filtered_tb = _process_traceback_frames(e.__traceback__)                    
    68 │   │   │   # To get the full stack trace, call:                                        
    69 │   │   │   # `tf.debugging.disable_traceback_filtering()`                                
❱  70 │   │   │   raise e.with_traceback(filtered_tb) from None                                
    71 │   │   finally:                                                                        
    72 │   │   │   del filtered_tb                                                             
    73                                                                                         
                                                                                            
 /usr/local/lib/python3.10/dist-packages/keras/utils/generic_utils.py:514 in validate_kwargs   
                                                                                            
   511 │   """Checks that all keyword arguments are in the set of allowed keys."""             
   512 │   for kwarg in kwargs:                                                                
   513 │   │   if kwarg not in allowed_kwargs:                                                   
 ❱ 514 │   │   │   raise TypeError(error_message, kwarg)                                        
   515                                                                                         
   516                                                                                          
   517 def default(method):          
```

**Comment by aminfardi-CD** [comment] 2023-09-06 18:21
Ran into this issue as well.

**Comment by pcuenca** [comment] 2023-09-06 18:23
I think you need to have `accelerate` installed.

**Comment by aminfardi-CD** [comment] 2023-09-06 20:13
@pcuenca I confirmed I have `accelerate` installed. Looking through huggingface docs, I actually don't see `device_map` parameter listed in the AutoModel parameters anymore. Wonder if it's been moved or deprecated?

**Comment by pcuenca** [comment] 2023-09-07 08:01
The following works for me with transformers `4.33.0` and accelerate `0.22.0`:

```python
import transformers
import torch
x = transformers.pipeline("text-generation", model="distilgpt2", device_map="auto", torch_dtype=torch.float16)
```

Please, make sure you are using recent versions of `transformers` and `accelerate`. If it still doesn't work, I'd open an issue in the `accelerate` repo, providing a minimal reproducible code snippet and details about your system.

Closing this issue now, I believe the blog post where this is mentioned is correct.

**Closed by pcuenca** 2023-09-07 08:01 UTC
